services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.5
    container_name: kibana
    environment:
      SERVER_NAME: mykibana.local
      SERVER_HOST: 172.20.0.2
      ELASTICSEARCH_HOSTS: '["http://${ES_HOST_1}:9200","http://${ES_HOST_2}:9200","http://${ES_HOST_3}:9200"]'
      ELASTICSEARCH_USERNAME: ${KBN_USER}
      ELASTICSEARCH_PASSWORD: ${KBN_PASS}
    networks:
      elastic:
        ipv4_address: 172.20.0.2
  nginx:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - $PWD/nginx-log:/var/log/nginx
      - $PWD/web_content:/usr/share/nginx/html:ro
      - $PWD/configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  
    networks:
      elastic:
        ipv4_address: 172.20.0.3

  web:
    image: httpd
    container_name: httpd_web
    ports:
      - "8081:80"
    networks:
      elastic:
        ipv4_address: 172.20.0.4
    depends_on:
      - fluentd
    logging: 
      driver: "fluentd"
      options:
        fluentd-address: 172.20.0.7:24224
        tag: httpd.access
    
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.2
    container_name: filebeat-nginx
    env_file:
      - .env
    volumes:
      - $PWD/configs/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - $PWD/nginx-log:/var/log/nginx:ro
      - $PWD/configs/nginx.yml:/usr/share/filebeat/modules.d/nginx.yml
    networks:
      elastic:
        ipv4_address: 172.20.0.5
    depends_on:
      - nginx

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.5
    container_name: logstash
    env_file:
      - .env
    networks:
      elastic:
        ipv4_address: 172.20.0.6
    volumes:
      - $PWD/configs/logstash.yml:/usr/share/logstash/config/logstash.yml
      - $PWD/configs/pipeline:/usr/share/logstash/pipeline
      - $PWD/sample-log/sample.log:/tmp/sample.log

  fluentd:
    build: .
    container_name: fluentd
    environment:
      - FLUENT_CONF=demo.conf
    env_file:
      - .env
    volumes:
      - $PWD/configs/fluentd/demo.conf:/fluentd/etc/fluent.conf
    networks:
      elastic:
        ipv4_address: 172.20.0.7
    
networks:
  elastic:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
