services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.5
    container_name: kibana
    environment:
      SERVER_NAME: mykibana.local
      SERVER_HOST: 172.20.0.2
      ELASTICSEARCH_HOSTS: '["http://192.168.122.97:9200","http://192.168.122.67:9200","http://192.168.122.89:9200"]'
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: 0fAJQrtTW7U6wuLlWvLE
    networks:
      elastic:
        ipv4_address: 172.20.0.2
  nginx:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - $PWD/nginx-log:/var/log/nginx
      - $PWD/web_content:/usr/share/nginx/html:ro
      - $PWD/configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      
    networks:
      elastic:
        ipv4_address: 172.20.0.3
    
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.2
    container_name: filebeat-nginx
    volumes:
      - $PWD/configs/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - $PWD/nginx-log:/var/log/nginx:ro
      - $PWD/configs/nginx.yml:/usr/share/filebeat/modules.d/nginx.yml
    networks:
      - elastic
    depends_on:
      - nginx
  
  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.5
    container_name: logstash
    networks:
      - elastic
    volumes:
      - $PWD:/configs/logstash.conf:/usr/share/logstash/config/logstash.yml
      - $PWD:/configs/pipeline:/usr/share/logstash/pipeline

networks:
  elastic:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
