filebeat.config.modules:
  path: /usr/share/filebeat/modules.d/*.yml
  reload.enabled: false
filebeat.inputs:
- type: filestream
  id: nginx-logs
  paths:
    - /var/log/nginx/*.log

output.elasticsearch:
  hosts: 
    - http://${ES_HOST_1}:9200
    - http://${ES_HOST_2}:9200
    - http://${ES_HOST_3}:9200
  username: ${ES_USER}
  password: ${ES_PASS}
  enabled: false
output.logstash:
  hosts:
    - logstash:5044
